adminUser: admin
adminPassword: grafana123

service:
  type: NodePort
  nodePort: 30300

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m

plugins:
  - grafana-clickhouse-datasource